# Generated by Django 3.1.6 on 2021-02-18 17:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_bio',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
