# Generated by Django 3.1.6 on 2021-02-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210218_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_bio',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
