# Generated by Django 3.1.6 on 2021-03-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210218_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_bio',
            new_name='hero_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_button',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_headline',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_description_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_description_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_description_3',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_name_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_name_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_name_3',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_quote_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_quote_2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_quote_3',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
