# Generated by Django 3.1.6 on 2021-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210323_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
