# Generated by Django 3.1.6 on 2021-03-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
