# Generated by Django 3.1.6 on 2021-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210323_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='auto_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='buisness_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insurance_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insurance_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='life_description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
