# Generated by Django 3.1.6 on 2021-03-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210324_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
