# Generated by Django 3.1.6 on 2021-03-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210324_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
