# Generated by Django 3.1.7 on 2021-06-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210412_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='google_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_button',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
