# Generated by Django 3.1.6 on 2021-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210222_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='to_address',
        ),
    ]
