# Generated by Django 3.1.6 on 2021-02-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210223_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpage'),
        ),
    ]
