# Generated by Django 3.1.6 on 2021-02-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210223_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpage'),
        ),
    ]
