# Generated by Django 3.1.6 on 2021-02-25 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0012_contactsuccesspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSuccessPage',
            new_name='ContactResponsePage',
        ),
    ]
