# Generated by Django 3.1.6 on 2021-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210323_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
