# Generated by Django 3.1.6 on 2021-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_commentmodel_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='visible',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='comments_toggle',
            field=models.BooleanField(default=True),
        ),
    ]
